In [1]:
import numpy as np
import gym
import time

import pybullet as p
import pybullet_data
import pybullet_envs
from stable_baselines3 import PPO

pybullet build time: Oct 14 2023 15:56:46


In [2]:
# train halfcheetah agent with PPO
env = gym.make("HalfCheetahBulletEnv-v0")
model = PPO("MlpPolicy", env, verbose=1)

/opt/homebrew/Caskroom/miniforge/base/envs/pybullet/lib/python3.8/site-packages/pybullet_envs/env_bases.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
/opt/homebrew/Caskroom/miniforge/base/envs/pybullet/lib/python3.8/site-packages/pkg_resources/__init__.py:2832: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/opt/homebrew/Caskroom/miniforge/base/envs/pybullet/lib/python3.8/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping y

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [3]:
model.learn(total_timesteps=10000, progress_bar=True)

Output()

argv[0]=
argv[0]=


---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | -1.3e+03 |
| time/              |          |
|    fps             | 1069     |
|    iterations      | 1        |
|    time_elapsed    | 1        |
|    total_timesteps | 2048     |
---------------------------------


-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | -1.21e+03   |
| time/                   |             |
|    fps                  | 912         |
|    iterations           | 2           |
|    time_elapsed         | 4           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.011739026 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.5        |
|    explained_variance   | -0.00227    |
|    learning_rate        | 0.0003      |
|    loss                 | 71.4        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0194     |
|    std                  | 0.995       |
|    value_loss           | 294         |
-----------------------------------------


-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | -1.13e+03   |
| time/                   |             |
|    fps                  | 873         |
|    iterations           | 3           |
|    time_elapsed         | 7           |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.009933983 |
|    clip_fraction        | 0.0842      |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.48       |
|    explained_variance   | 0.0453      |
|    learning_rate        | 0.0003      |
|    loss                 | 63.8        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0154     |
|    std                  | 0.994       |
|    value_loss           | 221         |
-----------------------------------------


-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | -1.16e+03   |
| time/                   |             |
|    fps                  | 861         |
|    iterations           | 4           |
|    time_elapsed         | 9           |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.012170074 |
|    clip_fraction        | 0.12        |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.46       |
|    explained_variance   | 0.0263      |
|    learning_rate        | 0.0003      |
|    loss                 | 37.4        |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0184     |
|    std                  | 0.988       |
|    value_loss           | 127         |
-----------------------------------------


-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1e+03       |
|    ep_rew_mean          | -1.15e+03   |
| time/                   |             |
|    fps                  | 850         |
|    iterations           | 5           |
|    time_elapsed         | 12          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.010693472 |
|    clip_fraction        | 0.0814      |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.43       |
|    explained_variance   | 0.00261     |
|    learning_rate        | 0.0003      |
|    loss                 | 82.3        |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0151     |
|    std                  | 0.984       |
|    value_loss           | 252         |
-----------------------------------------


In [4]:
env = gym.make("HalfCheetahBulletEnv-v0")
env.render("human")
env.reset()

argv[0]=
Version = 4.1 Metal - 83
Vendor = Apple
Renderer = Apple M1
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started


array([ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        , -0.2970886 ,  0.        ,
        0.12443632,  0.        , -0.37058067,  0.        ,  0.25909856,
        0.        , -0.02238874,  0.        ,  1.2332586 ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ], dtype=float32)

In [5]:
import gym

while 1:
  frame = 0
  score = 0
  restart_delay = 0
  obs = env.reset()
  while 1:
    time.sleep(1. / 60.)
    a = env.action_space.sample()
    obs, r, done, _ = env.step(a)
    score += r
    frame += 1
    still_open = env.render()
    if still_open == False:
      break
    if not done: continue
    if restart_delay == 0:
      print("score=%0.2f in %i frames" % (score, frame))
      restart_delay = 60 * 2  # 2 sec at 60 fps
    else:
      restart_delay -= 1
      if restart_delay == 0: break

/var/folders/ky/f89knrjx5953hm2lrfqmdxr80000gn/T/ipykernel_69657/368208843.py:15: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if still_open == False:


score=-1183.40 in 1000 frames
score=-1189.55 in 1000 frames
score=-1027.64 in 1000 frames
score=-1395.66 in 1000 frames
score=-1272.25 in 1000 frames
score=-1224.69 in 1000 frames
score=-1420.12 in 1000 frames


: 

In [6]:
obs = env.reset()
done = False
while True:
    time.sleep(1/60)
    action, _info = model.predict(obs)
    obs, rewards, done, _info = env.step(action)
    env.render()

[-0.26621962  0.4900435  -0.35493785 -0.08770898  1.         -0.58692235]
[ 1.         -0.79363054 -0.3879865  -0.7284731   1.         -0.99755055]
[-1.         -0.5534133   0.77166533  0.74640054 -0.03434602 -0.11041506]
[ 0.5912868  -1.          0.9616269  -0.8608372  -0.22410634 -1.        ]
[ 1.          0.82302296 -1.          0.62695205 -1.         -0.19852814]
[-0.5662042   0.22448964 -1.         -1.         -1.         -0.67209035]
[-0.28834802 -0.03102631 -1.         -0.7575306   0.7039751  -0.29693356]
[-0.651582   -1.         -0.2765222  -0.2992195   0.7051203  -0.34846428]
[ 0.28138188  0.98403007  0.62066203  0.14171411 -0.456013    0.14758107]
[ 0.9714807   0.7182723  -0.32658204  0.7462949   0.52552754  0.33675492]
[-0.8827123  -0.43630373  1.         -0.7661882   1.         -1.        ]
[0.48594165 0.09595081 0.13144347 0.6932161  1.         1.        ]
[ 0.23415196 -0.6656243   0.63038504  1.         -0.71338356  1.        ]
[ 0.1167216  -1.         -1.         -0.8030

In [19]:
env.close()

numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed


: 